on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: 37 20 * * *
name: Semgrep
rules:
  - id: detect-xss
    name: Detect potential XSS (Cross-Site Scripting) vulnerabilities
    message: "Potential XSS vulnerability detected: $@payload"
    severity: ERROR
    languages:
      - javascript
    patterns:
      - pattern: "document.write($...)"
      - pattern: "document.writeln($...)"
      - pattern: "innerHTML\s*=\s*$..."
      - pattern: "setAttribute\s*\(\s*\"(?:src|href)\"\s*,\s*$..."

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
