name: Semgrep

on:
  pull_request:
    branches:
      - "*"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep
        id: semgrep_run
        run: |
          semgrep ci --json > semgrep_results.json

      - name: Check and Comment on blocking issues
        if: failure()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const semgrepResults = JSON.parse(fs.readFileSync('semgrep_results.json', 'utf8'));

            let issueDetails = '';
            if (semgrepResults.results && semgrepResults.results.length > 0) {
              issueDetails = semgrepResults.results.map(result => {
                return `${result.check_id}: ${result.extra.message} at ${result.path}:${result.start.line}`;
              }).join('\n');

              const body = `Blocking issues detected. Please review the code:\n${issueDetails}`;
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }